draw_char = 0;
text = ["* Wawawawa,^1 this is a textbox.", "* Come be a textbox with me\n  twin."];
expression = [];
page = 0;
use_box = false;
box_pos = "bottom";
fnt = fnt_main;
text_speed = 1;
delayed = false;
delay_time = 15;
delay_timer = 0;
snd = snd_generic_text;
snd_delay = 1;
snd_count = 0;
done = false;
can_accept = true;
can_skip = true;
paused = false;
typing = true;
line_sep = 0;
siner = 0;
current_expression = "";
reset = function() {
    draw_char = 0;
    page = 0;
    done = false
}
depth = -9999999999;