draw_char = 0;
text = ["* Wawawawa,^1 this is a textbox.", "* Come be a textbox with me\n  twin."];
expression = [];
page = 0;
use_box = false;
fnt = fnt_main;
text_speed = 1;
delayed = false;
delay_time = 15;
delay_timer = 0;
snd = snd_generic_text;
random_snd = [snd_tenna1, snd_tenna2, snd_tenna3, snd_tenna4, snd_tenna5, snd_tenna6, snd_tenna7, snd_tenna8, snd_tenna9, snd_tenna10];
snd_delay = 1;
snd_count = 0;
done = false;
can_accept = true;
can_skip = true;
paused = false;
typing = true;
line_sep = 0;
siner = 0;
current_expression = "";
move_on_destroy = true;
tenna_speak = false;
reset = function() {
    draw_char = 0;
    page = 0;
    done = false
}
depth = -9999999999;